language: node_js
node_js:
  - 0.6

before_install:
  - sudo apt-get install libgc1c2
  - curl http://haxe.org/file/hxinst-linux.tgz | tar zxf -
  - echo y | sudo ./hxinst-linux > /dev/null
  - echo | haxelib setup
  - haxelib install nme
  - haxelib install hxcpp

before_script:
  - ant haxelib

script:
  - "cd tests && haxe compile.hxml"