language: java

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update -y
  - sudo apt-get install haxe -y
  - mkdir -p ~/.haxe/lib
  - echo ~/.haxe/lib | haxelib setup
  - haxelib install nme || true

script:
  - ant clean build unit